// packages/angular-example/src/app/order-list/index.ts
import { Atom } from '@borshch/utilities';
import { Component } from '@angular/core';
import { RenderOrderList, UpdateOrderList, OpenOrder, RemoveOrderFromList } from '@clean-architecture-playground/core';
import { dataStore, notifier } from '@clean-architecture-playground/core/dummy-dependencies';
import { AngularNavigator } from '../dependencies/navigator';
import {presentOrderList} from './presenter';

@Component({
  selector: 'app-order-list-page',
  standalone: false,
  templateUrl: './view.html',
  styleUrl: './view.css'
})
export class OrderListPage {
  constructor(
    navigator: AngularNavigator
  ) {
    this.#navigator = navigator
    this.#useCases = {
      renderOrderList: RenderOrderList({
        presentation: this.#presentation,
        updateOrderList: UpdateOrderList({
          presentation: this.#presentation,
          dataStore,
          notifier,
        }),
      }),
      updateOrderList: UpdateOrderList({
        presentation: this.#presentation,
        dataStore,
        notifier,
      }),
      removeOrderFromList: RemoveOrderFromList({
        presentation: this.#presentation,
        dataStore,
        notifier,
      }),
      openOrder: OpenOrder({
        presentation: this.#presentation,
        navigator: this.#navigator,
        notifier,
      }),
    }
  }

  ngOnInit() {
    this.#unsubscribeFromPresentation = this.#presentation.subscribe((model: any) => {
      this.viewModel = presentOrderList(model)
    })
    this.controller.initialize()
  }

  ngOnDestroy() {
    this.#unsubscribeFromPresentation()
  }

  viewModel = {} as any

  get orders() { // TODO: ivanko - move to presenter and test it
    return this.viewModel.loading && !this.viewModel.list?.length
      ? Array(3).fill(emptyOrderPresentation)
      : this.viewModel.list
  }
  
  #presentation = new Atom()
  #navigator

  #useCases

  controller = {
    initialize: () => this.#useCases.renderOrderList(),
    openOrder: (id: string) => this.#useCases.openOrder(id),
    refresh: () => this.#useCases.updateOrderList({ refresh: true }),
    loadMore: () => this.#useCases.updateOrderList(),
    deleteOrder: (event: MouseEvent, orderId: string) => {
      event.stopPropagation()
      this.#useCases.removeOrderFromList(orderId)
    },
  }
  
  #unsubscribeFromPresentation: any
}

const emptyOrderPresentation = {createdDate: '...', user: '...', sum: '...', paymentStatus: '...', fulfillmentStatus: '...'}

// packages/vue-example/src/components/order-list/OrderList.vue
<template src="./view.html"></template>
<style src="./view.css"></style>

<script>
import {ref, onBeforeMount, onBeforeUnmount} from 'vue'
import OrderListItem from '@/components/order-list/OrderListItem.vue'
import {Atom} from '@borshch/utilities';
import {OpenOrder, RenderOrderList, RemoveOrderFromList, UpdateOrderList, presentOrderList} from '@clean-architecture-playground/core'
import {dataStore, notifier} from '@clean-architecture-playground/core/dummy-dependencies'
import {appNavigator} from '../../dependencies/navigator.js';

const present = (model) => {
  return model.loading && !model.list.length
    ? {
      ...model,
      list: Array(3).fill(undefined).map((_, index) => ({
        id: `placeholder${index}`,
        createdDate: '...',
        user: '...',
        sum: '...',
        paymentStatus: '...',
        fulfillmentStatus: '...',
      })),
    }
    : model
}

export default {
  name: 'OrderList',
  components: {
    OrderListItem
  },
  setup() {
    let unsubscribeFromPresentation
    const controller = ref({})
    const viewModel = ref({})

    onBeforeMount(() => {
      const presentation = new Atom()
      const updateOrderList = UpdateOrderList({presentation, dataStore, notifier})
      const renderOrderList = RenderOrderList({presentation, updateOrderList})
      const removeOrderFromList = RemoveOrderFromList({dataStore, notifier, presentation})
      const openOrder = OpenOrder({
        notifier, presentation,
        navigator: appNavigator,
      })

      controller.value = {
        initialize: () => renderOrderList(),
        refresh: () => updateOrderList({refresh: true}),
        loadMore: () => updateOrderList(),
        remove: removeOrderFromList,
        open: openOrder,
      }

      unsubscribeFromPresentation = presentation.subscribe((model) => {
        viewModel.value = present(presentOrderList(model))
      })

      controller.value.initialize()
    })

    onBeforeUnmount(() => {
      unsubscribeFromPresentation()
    })

    return {
      viewModel,
      controller,
    }
  }
}

</script>
