// packages/react-example/src/order-list/index.jsx
import {Atom} from '@borshch/utilities';
import {OpenOrder, RenderOrderList, RemoveOrderFromList, UpdateOrderList} from '@clean-architecture-playground/core'
import {dataStore, notifier} from '@clean-architecture-playground/core/dummy-dependencies'
import {appNavigator} from '../dependencies/navigator.jsx'
import {OrderListView} from './view.jsx'
import {useIntegration} from '../common/hooks.js';
import {presentOrderList} from './presenter.js';

export const OrderList = () => {
  const {controller, viewModel} = useIntegration(makeOrderListIntegration)
  
  return viewModel && <OrderListView viewModel={viewModel} controller={controller} />
}

const makeOrderListIntegration = () => {
  const presentation = new Atom()
  const updateOrderList = UpdateOrderList({presentation, dataStore, notifier})
  const renderOrderList = RenderOrderList({presentation, updateOrderList})
  const removeOrderFromList = RemoveOrderFromList({dataStore, notifier, presentation})
  const openOrder = OpenOrder({
    notifier, presentation,
    navigator: appNavigator,
  })

  return {
    presentation,
    present: presentOrderList,
    controller: {
      initialize: () => renderOrderList(),
      refresh: () => updateOrderList({refresh: true}),
      loadMore: () => updateOrderList(),
      remove: (event, id) => {
        event.stopPropagation()
        return removeOrderFromList(id);
      },
      open: openOrder,
    },
  }
}

// packages/vue-example/src/components/order-list/OrderList.vue
<template src="./view.html"></template>
<style src="./view.css"></style>

<script>
import OrderListItem from '@/components/order-list/OrderListItem.vue'
import {Atom} from '@borshch/utilities';
import {OpenOrder, RenderOrderList, RemoveOrderFromList, UpdateOrderList, presentOrderList} from '@clean-architecture-playground/core'
import {dataStore, notifier} from '@clean-architecture-playground/core/dummy-dependencies'
import {appNavigator} from '../../dependencies/navigator.js';
import {useIntegration} from '../../common/integration.js';

const present = (model) => {
  const viewModel = presentOrderList(model)
  return viewModel.loading && !viewModel.list.length
    ? {
      ...viewModel,
      list: Array(3).fill(undefined).map((_, index) => ({
        id: `placeholder${index}`,
        createdDate: '...',
        user: '...',
        sum: '...',
        paymentStatus: '...',
        fulfillmentStatus: '...',
      })),
    }
    : viewModel
}

const makeOrderListIntegration = () => {
  const presentation = new Atom()
  const updateOrderList = UpdateOrderList({presentation, dataStore, notifier})
  const renderOrderList = RenderOrderList({presentation, updateOrderList})
  const removeOrderFromList = RemoveOrderFromList({dataStore, notifier, presentation})
  const openOrder = OpenOrder({
    notifier, presentation,
    navigator: appNavigator,
  })

  const controller = {
    initialize: () => renderOrderList(),
    refresh: () => updateOrderList({refresh: true}),
    loadMore: () => updateOrderList(),
    remove: removeOrderFromList,
    open: openOrder,
  }

  return {controller, present, presentation}
}

export default {
  name: 'OrderList',
  components: {
    OrderListItem
  },
  setup() {
    return useIntegration(makeOrderListIntegration)
  }
}

</script>
