// packages/react-native-example/src/order/index.js
import {BackHandler} from 'react-native';
import {ChangeOrderField, CloseOrder, RenderOrder, SaveOrder} from '@clean-architecture-playground/core';
import {CommonScreen} from '../common/common-screen';
import {OrderView} from './view';

export class Order extends CommonScreen {
  static getOptions({route: {params: {id}}}) {
    return {
      title: `Order ${id}`, 
      // headerRight: () => (<Button title='Save' onPress={() => alert('Save Pressed')} />),
    }
  }

  View = OrderView

  controller = {
    initialize: () => this.#useCases.renderOrder(this.props.route.params.id),
    change: (name, value) => this.#useCases.changeOrderField(name, value),
    save:() => this.#useCases.saveOrder(),
    close: () => this.#useCases.closeOrder(),
  }

  componentDidMount() {
    super.componentDidMount()
    this.props.navigator.onClose(this.controller.close)
  }

   #useCases = {
    renderOrder: RenderOrder({
      presentation: this.presentation, 
      dataStore: this.context.dataStore,
    }),
    changeOrderField: ChangeOrderField({
      presentation: this.presentation,
    }),
    saveOrder: SaveOrder({
      presentation: this.presentation,
      dataStore: this.context.dataStore,
      navigator: this.props.navigator,
      notifier: this.context.notifier,
    }),
    closeOrder: CloseOrder({
      presentation: this.presentation,
      navigator: this.props.navigator,
      notifier: this.context.notifier,
    })
  }
}

// packages/vue-example/src/components/order/index.vue
<template src="./view.html"></template>
<style scoped src="./view.css"></style>

<script>
import {Atom} from '@borshch/utilities'
import {useRoute} from 'vue-router'
import {ChangeOrderField, CloseOrder, RenderOrder, SaveOrder} from '@clean-architecture-playground/core'
import {dataStore, notifier} from '@clean-architecture-playground/core/dummy-dependencies'
import {appNavigator} from '../../dependencies/navigator.js'
import {useIntegration} from '../../common/integration.js'
import {presentOrder} from './presenter.js'

const makeOrderIntegration = (orderId) => {
  const presentation = new Atom()
  const renderOrder = RenderOrder({presentation, dataStore})
  const changeOrderField = ChangeOrderField({presentation})
  const closeOrder = CloseOrder({presentation, navigator: appNavigator, notifier})
  const saveOrder = SaveOrder({presentation, dataStore, navigator: appNavigator, notifier})

  const controller = {
    initialize: () => renderOrder(orderId),
    change: ({currentTarget: {name, value}}) => changeOrderField(name, value),
    close: closeOrder,
    save: saveOrder,
 }

  return {
    controller, 
    presentation,
    present: presentOrder, 
  }
}

export default {
    name: 'Order',
    setup() {
      const route = useRoute()
      const orderId = route.query.id

      return useIntegration(makeOrderIntegration, orderId)
   },
}
</script>
