// packages/react-example/src/order/index.jsx
import {useEffect, useState, useRef} from 'react'
import {useSearchParams} from 'react-router';
import {Atom} from '@borshch/utilities';
import {dataStore, notifier} from '@clean-architecture-playground/core/dummy-dependencies'
import {appNavigator} from '../dependencies/router.jsx';
import {ChangeOrderField, CloseOrder, presentOrder, RenderOrder, SaveOrder} from '@clean-architecture-playground/core';
import {OrderView} from './view.jsx';

export const Order = () => {
  const [urlSearchParams] = useSearchParams()
  const {controller, viewModel} = useCleanArchitecture(urlSearchParams.get('id'))

  return <OrderView viewModel={viewModel} controller={controller} />
}

const useCleanArchitecture = (id) => {
  const presentation = new Atom()
  const renderOrder = RenderOrder({dataStore, presentation})
  const changeOrderField = ChangeOrderField({presentation})
  const closeOrder = CloseOrder({
    presentation, notifier,
    navigator: appNavigator,
  })
  const saveOrder = SaveOrder({
    presentation, notifier,
    navigator: appNavigator,
  })

  const [viewModel, setViewModel] = useState({});
  const controller = useRef({})

  useEffect(() => {
    controller.current = {
      initialize: () => renderOrder(id),
      change: ({target: {name, value}}) => changeOrderField(name, value),
      close: () => closeOrder(),
      save: () => saveOrder(),
    }
    
    const unsubscribe = presentation.subscribe((model) => 
      setViewModel(Object.keys(model.data).length ? presentOrder(model) : model))
    controller.current.initialize()
  	
    return () => unsubscribe();
  }, []);

  return {
    viewModel,
    controller: controller.current,
  }
}

// packages/angular-example/src/app/order/index.ts
import { Component } from '@angular/core'
import { Atom } from '@borshch/utilities'
import { dataStore, notifier } from '@clean-architecture-playground/core/dummy-dependencies'
import { ChangeOrderField, CloseOrder, RenderOrder, SaveOrder } from '@clean-architecture-playground/core'
import { AngularNavigator } from '../dependencies/navigator'
import {presentOrder} from './presenter'
import {Subscription} from 'rxjs'

@Component({
  selector: 'app-order-page',
  standalone: false,
  templateUrl: './view.html',
  styleUrl: './view.css'
})
export class OrderPage {
  constructor(navigator: AngularNavigator) {
    this.#navigator = navigator
    this.#useCases = {
      renderOrder: RenderOrder({
        dataStore,
        presentation: this.#presentation,
      }),
      closeOrder: CloseOrder({
        notifier,
        navigator: this.#navigator,
        presentation: this.#presentation,
      }),
      saveOrder: SaveOrder({
        dataStore, notifier,
        navigator: this.#navigator,
        presentation: this.#presentation,
      }),
      changeOrderField: ChangeOrderField({
        presentation: this.#presentation,
      }),
    }
  }

  viewModel = {} as any

  controller = {
    initialize: () => {
      this.#queryParamsSubscriber = this.#navigator.currentRoute.queryParams.subscribe(({id}) => {
        this.#useCases.renderOrder(id)
        this.#queryParamsSubscriber?.unsubscribe()
      })
    },
    change: (event: Event) => {
      const {target} = event
      const {name, value} = target as HTMLInputElement
      this.#useCases.changeOrderField(name, value)
    },
    save: () => this.#useCases.saveOrder(),
    close: () => this.#useCases.closeOrder(),
  }

  ngOnInit() {
    this.#unsubscribeFromPresentation = this.#presentation.subscribe((model: any) => {
      this.viewModel = presentOrder(model)
    })
    this.controller.initialize()
  }

  ngOnDestroy() {
    this.#unsubscribeFromPresentation()
    this.#queryParamsSubscriber.unsubscribe()
  }

  get dataIsEmpty() { //TODO: ivanko - move to presenter
    return Object.keys(this.viewModel.data).length === 0
  }
  
  #useCases
  #navigator
  #presentation = new Atom()
  #queryParamsSubscriber!: Subscription
  #unsubscribeFromPresentation!: () => void
}
